name: kids application build
on:
  push:
    branches: 
      - main 
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: docker frontend build
        run: docker run -d --name luxe-nginx -p 80:80 -v "${PWD}:/usr/share/nginx/html" nginx
      - name: container checking 
        run: docker ps
      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}
      - name: Checking Docker Login
        run: docker info
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check if docker image exists
        run: docker images
      
     